### ISSUE TITLE
Interactive selection using draw controls

### ISSUE THREAD

**Issue by benbovy** [davidbrochart/xarray_leaflet#1]
It would be great if somehow we could draw a rectangle on the map (using ipyleaflet's controls) and get the selected region as a new `xarray.DataArray` object.

**Comment by davidbrochart** [comment]
Indeed, and thanks for the first issue/feature request! I will work on that soon.

**Comment by benbovy** [comment]
Thanks for working on `xarray_leaflet`! Integrated in the [pangeo](http://pangeo.io/) ecosystem this could provide a very nice alternative to [geemap](https://github.com/giswqs/geemap) that doesn't rely on Google Earth Engine.

I hope to contribute soon (perhaps first on more simple features than this one).

**Comment by davidbrochart** [comment]
@benbovy I have implemented a solution in #17. Any feedback is very welcome!
