### ISSUE TITLE
Setting layer name shown under the layer control

### ISSUE THREAD

**Issue by giswqs** [davidbrochart/xarray_leaflet#12]
Is it possible to set the layer name shown under the layer control? Currently, it seems the default layer name is empty. I tried using `l.name = 'layer name'`, but it has no effect. It would be great if the `da.leaflet.plot()` has a name argument that can be set directly. Thanks.  

![](https://i.imgur.com/Vbg7W8a.png)

**Comment by davidbrochart** [comment]
Thanks for your suggestion @giswqs, I will try to work on it soon. Maybe we could use the `DataArray` name? Similarly, plotting a `Dataset` (#2) would use each array's name.

**Comment by giswqs** [comment]
@davidbrochart Sounds good. So basically, users can set `da.name`, then your `da.leaflet.plot()` function automatically uses `da.name` as the layer name to show under the layer control. Am I correct?

```
da = xr.open_rasterio('/path/to/file')
da.name = 'layer name'
l = da.leaflet.plot(m, x_dim='x', y_dim='y')
```

**Comment by davidbrochart** [comment]
Yes, that's the plan. But it could also be possible to set it as a keyword argument of the plot function in the case of a `DataArray` as you suggested.

**Comment by giswqs** [comment]
Sounds great! Looking forward to it. I will be adding xarray_leaflet as a dependency for geemap. I plan to add a function (e.g., `Map.add_raster(file_path, layer_name)`) that wraps `da.leaflet.plot()` so that users can use one line of code to load local raster datasets to geemap.

**Comment by davidbrochart** [comment]
Awesome!

**Comment by giswqs** [comment]
I was able to customize the layer name. [Here](https://github.com/giswqs/geemap/blob/master/geemap/geemap.py#L1842) is the source code. 

![](https://i.imgur.com/EwUDU5f.gif)

**Comment by davidbrochart** [comment]
So it looks like setting the layer name works fine?

**Comment by giswqs** [comment]
Yes, it works with geemap. But I would still suggest you add the layer_name argument to the `plot()` function so that non-GEE users can still use ipyleaflet to load rasters. Otherwise, when multiple local raster layers are added, only the last one added will be listed under the layer control.

**Comment by crendl** [comment]
> I would still suggest you add the layer_name argument to the `plot()` function

I second that suggestion!
Regards

**Comment by davidbrochart** [comment]
Sorry, I didn't have much time to work on xarray-leaflet lately. There will be a JupyterCon sprint on ipyleaflet, where we could also work on xarray-leaflet. It would be great if you could participate!

**Comment by davidbrochart** [comment]
The layer name is now set to the DataArray name (see https://github.com/davidbrochart/xarray_leaflet/commit/66536e0f6be8de088d1594d2defdf27051c45ca5).
