### ISSUE TITLE
Problem displaying GeoTIFF

### ISSUE THREAD

**Issue by giswqs** [davidbrochart/xarray_leaflet#13]
I was trying to display a small DEM (epsg:4326) on the map. However, I noticed the DEM was being displayed at three locations with varying sizes. Only the smallest one at the upper left is the correct one. 

[Here](https://gist.github.com/giswqs/60cba5e22c0b850ee039f4faec795334) is the notebook to reproduce the issue. 

![](https://i.imgur.com/Na81ZkH.gif)

**Comment by davidbrochart** [comment]
It works fine on my local setup but it's not even pushed to master yet, we need an ipyleaflet release before.
I will let you know when it's done, thanks for reporting the issue.

**Comment by davidbrochart** [comment]
It should be fixed in v0.1.9.

**Comment by giswqs** [comment]
It seems there is still some weird black background when displaying GeoTIFF with v0.1.9. 

[Here](https://gist.github.com/giswqs/60cba5e22c0b850ee039f4faec795334) is the notebook to reproduce the issue. 

![](https://i.imgur.com/heGfVeM.gif)

**Comment by davidbrochart** [comment]
Can you try removing `da = xr.where(da==nan, np.nan, da)`?

**Comment by giswqs** [comment]
Fantastic! Removing that line solve the issue. I will be integrating xarray_leaflet into geemap shortly. Loading local datasets and cloud optimized GeoTIFF is a highly desirable feature. Thank you very much for your excellent work!

**Comment by giswqs** [comment]
BTW, can the color ramp be customized?

**Comment by davidbrochart** [comment]
> Fantastic! Removing that line solves the issue.

I don't fully understand why removing this line makes it work though.

> I will be integrating xarray_leaflet into geemap shortly. Loading local datasets and cloud optimized GeoTIFF is a highly desirable feature. Thank you very much for your excellent work!

Thanks! I'm excited to see what you will do with xarray-leaflet, I think that to have you using it is a great opportunity to improve it. I'll try to keep up with your feedback!

> BTW, can the color ramp be customized?

Yes, for now it's just a matplotlib colormap so you can tweak it, see [this example](https://github.com/davidbrochart/xarray_leaflet/blob/master/examples/custom_projection.ipynb). Feedback is also welcome in #14.

**Comment by giswqs** [comment]
I just figured it out. 

![](https://i.imgur.com/AvXe2cc.png)
