### ISSUE TITLE
Display colorbar

### ISSUE THREAD

**Issue by davidbrochart** [davidbrochart/xarray_leaflet#14]
We need a way to display a colorbar. The colormap currently uses matplotlib, so the easiest way is to show the colorbar with matplotlib and show it outside the map. It should also be possible to show it inside the map.
Another way would be to use a [custom legend control in Leaflet](https://leafletjs.com/examples/choropleth), but we need a way to match matplotlib's colormap. Or use Leaflet's colormap instead of matplotlib's.

**Comment by giswqs** [comment]
In geemap, I generate the legend (with discrete values) using HTML, and then add a HTML widget in ipyleaflet to display it. Not quite sure about continuous colormap. 

![](https://i.imgur.com/xiKshVY.png)

**Comment by davidbrochart** [comment]
Interesting. We could also use branca as in https://github.com/jupyter-widgets/ipyleaflet/blob/master/examples/Choropleth.ipynb.

**Comment by giswqs** [comment]
The branca colormap can be printed out in a notebook cell. So the problem would be to customize it (size, orientation, etc) and add it into the map?

![](https://i.imgur.com/tSH59vk.png)

**Comment by davidbrochart** [comment]
That could be, yes. We also need to have an equivalent matplotlib colormap in Python [when we apply the colormap](https://github.com/davidbrochart/xarray_leaflet/blob/0090dc6619ea8602d01f8f5a80c6ad0477130e86/xarray_leaflet/xarray_leaflet.py#L254-L255). I don't know if we can use branca for that too.

**Comment by davidbrochart** [comment]
Done in #33.
