### ISSUE TITLE
open_rasterio masked=True

### ISSUE THREAD

**Issue by snowman2** [davidbrochart/xarray_leaflet#15]
Just wanted to point out the masked=True and the mask_and_scale=True options. Based on your getting started example, I figured this would be helpful.

**Comment by snowman2** [comment]
https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray-open-rasterio

**Comment by davidbrochart** [comment]
Thanks, I will use it. I think there is a typo:
**masked** _(bool, optional)_ – If True, read the mask and ~to~ set values to NaN.

**Comment by snowman2** [comment]
Indeed - looks like the mask_and_scale docstring could be updated as well.
