### ISSUE TITLE
raster doesn't display in voila

### ISSUE THREAD

**Issue by 12rambau** [davidbrochart/xarray_leaflet#19]
The rasters are not displayed on the map when the notebook is run with voila. 

This bug has been reported in [#143](https://github.com/giswqs/geemap/issues/143) of the geemap repository but I prefer to report it here as it seems to be linked to xarray_leaflet. 

I'll be glad to help

**Comment by davidbrochart** [comment]
Thanks for reporting @12rambau, any contribution is very welcome!

**Comment by 12rambau** [comment]
I tried to dig in the files but I couldn't find where is the linked between the generated files and the map

**Comment by davidbrochart** [comment]
So Leaflet makes HTTP GET requests for the tile files it is currently showing, and it is served by the Jupyter server through [this handler](https://github.com/davidbrochart/xarray_leaflet/blob/16db44ec8f7eaff6d31967241d31df4ad5d3b92d/xarray_leaflet/handler.py#L12-L52).
I thought I made it work with Voila by changing the [base URL](https://github.com/davidbrochart/xarray_leaflet/blob/16db44ec8f7eaff6d31967241d31df4ad5d3b92d/xarray_leaflet/xarray_leaflet.py#L260-L262), this might be where a change is needed.

**Comment by 12rambau** [comment]
I don't see any release since july so I assumed this modification only exist in the latest master branch. 
I donwloaded the repository and using the master branch, it has quite modified the output. I launch the `introduction.ipynb` notebook from the examples.

Using the V0.1.10, I get:
- this image in notebooks
<img width="987" alt="Capture d’écran 2020-10-06 à 18 43 33" src="https://user-images.githubusercontent.com/12596392/95231782-e253d100-0803-11eb-8cdf-56413e83be4e.png">
- this image in voila dashboard (doesn't display the raster)
<img width="1243" alt="Capture d’écran 2020-10-06 à 18 43 41" src="https://user-images.githubusercontent.com/12596392/95231797-ea137580-0803-11eb-970e-0f00dc77cee2.png">

and both contains the raster layer, it just doesn't appear on the leaflet map in voila. 

Using the latest master branch:
- this image in notebooks:
<img width="980" alt="Capture d’écran 2020-10-06 à 18 46 40" src="https://user-images.githubusercontent.com/12596392/95232198-732aac80-0804-11eb-98bd-0a19f97cd0f9.png">
- this image in voila:
<img width="1247" alt="Capture d’écran 2020-10-06 à 18 47 19" src="https://user-images.githubusercontent.com/12596392/95232214-7887f700-0804-11eb-970a-c5db670bae56.png">

So no images in both situation but the voila one has loaded the layer.

Can you confirm that you have the same outputs and that it's not coming from my env ?

**Comment by davidbrochart** [comment]
The master branch works because I'm developing on it, but for Voila I didn't investigate yet.

**Comment by 12rambau** [comment]
> The master branch works because I'm developing on it, but for Voila I didn't investigate yet.

works or doesn't work ? (On my side the example doesn't work anymore)  

I'll start from the v0.1.10 as it's the last stable version, and see if I can figure out something on my side.

**Comment by davidbrochart** [comment]
It works on my side. Yes you can use v0.1.10, the changes after that have nothing to do with the Voila issue.

**Comment by 12rambau** [comment]
It works on my personal computer as well congrats ! 
This feature was required for me on a professional server where I don't have the right to install manually new lib. Are you considering creating a new release of the lib. so that my boss accept to install it ?

**Comment by davidbrochart** [comment]
Yes, I'll try to make a release tonight.

**Comment by 12rambau** [comment]
Thank you for the release. I've been able to test it on several env. to pinpoint what's wrong with mine. I cannot actually make it work on a minimal installation (fresh conda with only xarray-leaflet). 

The loading wheel starts but nothing is displayed. As shown in my previous messages, the map stay dark.
Have you tried it on a fresh installation ?

**Comment by davidbrochart** [comment]
Yes, it works on my side in a fresh conda installation.
Does it work in the notebook?

**Comment by 12rambau** [comment]
I wanted to reproduce the behavior I get this afternoon, and of course it worked. let's wait a bit, I'll do more tests before bothering you again.

**Comment by davidbrochart** [comment]
I made two releases in a row, maybe you got the one where there was a bug.
