### ISSUE TITLE
Local raster are not displayed when using a sub 'notebooks' folder

### ISSUE THREAD

**Issue by ingdanielguerrero** [davidbrochart/xarray_leaflet#23]
I am working in a cloud environment that stores production notebooks in a `/shared/notebooks/` path... digging into `xarray_leaflet` code [I saw ](https://github.com/davidbrochart/xarray_leaflet/blob/700a91c9310fe4406ed322c7f9c25b90cddf46ab/xarray_leaflet/xarray_leaflet.py#L265) that when the module states the `base_url`, is using the word 'notebooks'. So in my case, it will cause a wrong URL referencing and will point to nowhere.
I doubt posting the issue here but as many people could store its notebooks in that folder, would be better if this is fixed in the module.

I was thinking instead of finding the last occurrence, just get the first.

**Comment by davidbrochart** [comment]
But then if you have a `notebooks` folder we could be in Voila, so this code is definitely not great. If you have any idea how to make it better, don't hesitate to open a PR.

**Comment by ingdanielguerrero** [comment]
I made a simple PR, I hope I'm not missing anything.
