### ISSUE TITLE
Tile doesn't display if the notebook folder is called 'notebooks' or 'voila'

### ISSUE THREAD

**Issue by 12rambau** [davidbrochart/xarray_leaflet#28]
As referenced in (sepal_ui #35)[https://github.com/12rambau/sepal_ui/issues/35], Local raster images are not being displayed in voilá dashboards nor Jupyter SEPAL dashboards, the problem comes up when the xarray_leaflet module is [stating](https://github.com/davidbrochart/xarray_leaflet/blob/700a91c9310fe4406ed322c7f9c25b90cddf46ab/xarray_leaflet/xarray_leaflet.py#L265) the base_url, using the 'notebooks' word.

The sepal module dashboards are being stored in /shared/notebooks/, so the condition is trying to find the last 'notebook' word, but as there are two occurrences in the URL, it will take the second, causing confusion and pointing to nowhere.

**Comment by ingdanielguerrero** [comment]
I thought it was fixed with #25. Thanks.
