### ISSUE TITLE
can't see data on map

### ISSUE THREAD

**Issue by rosatrancoso** [davidbrochart/xarray_leaflet#34]
Hi David
Congratulations on the package, I'm really looking forward to use it, but I simply can't see any data on the map.

See notebook [test_xarray_leaflet_simple.ipynb](https://github.com/rosatrancoso/docker-scipy-notebook/blob/master/test_xarray_leaflet_simple.ipynb)

This is probably not an issue with your package but with my jupyter setting, but maybe you could shed some light. I don't know where else to ask. 

I'm using Jupyter Lab from the `jupyter/scipy-notebook:703d8b2dcb88` docker image and have all the python packages and widgets seemly working properly: xarray, ipywidgets, ipyleaflet, ipyspin.

- Here is my [Dockerfile](https://github.com/rosatrancoso/docker-scipy-notebook/blob/master/Dockerfile.mamba_gis)
- Here is the running container [conda list](https://github.com/davidbrochart/xarray_leaflet/files/5812558/conda_list.txt)
- I tested ipyspin with your [example notebook](https://github.com/davidbrochart/ipyspin/blob/master/examples/introduction.ipynb) 

And also:

`jupyter --version`

      jupyter core     : 4.7.0
      jupyter-notebook : 6.1.6
      qtconsole        : not installed
      ipython          : 7.19.0
      ipykernel        : 5.4.2
      jupyter client   : 6.1.7
      jupyter lab      : 2.2.9
      nbconvert        : 6.0.7
      ipywidgets       : 7.6.2
      nbformat         : 5.0.8
      traitlets        : 5.0.5

`jupyter labextension list`

    JupyterLab v2.2.9
    Known labextensions:
       app dir: /opt/conda/share/jupyter/lab
            @bokeh/jupyter_bokeh v2.0.4  enabled  OK
            @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
            ipyspin v0.1.2  enabled  OK
            jupyter-leaflet v0.13.5  enabled  OK
            jupyter-matplotlib v0.7.4  enabled  OK

running with:
- Docker version 19.03.14
- Ubuntu 18.04.4 LTS (Bionic Beaver)

Please let me know if you need more info.

Cheers
Rosa

**Comment by davidbrochart** [comment]
Hi Rosa,

Thanks for the kind words!
The problem is that xarray-leaflet currently expects a coordinate reference system (CRS), and we rely on [rioxarray](https://corteva.github.io/rioxarray/stable/getting_started/crs_management.html) for that. Same for [nodata management](https://corteva.github.io/rioxarray/stable/getting_started/nodata_management.html). I tried your example with the following code and it works on my side:
```python
import rioxarray

da = da.rio.write_crs(4326)  # WGS 84
da = da.rio.write_nodata(np.nan)

l = da.leaflet.plot(m, colormap=plt.cm.viridis)
```
Please let me know if that solves you issue.

David.

**Comment by rosatrancoso** [comment]
Hi David

Thank you for your reply.
Indeed my "simple" example didn't have any projection set, but it still doesn't show anything.
Actually the first thing I tried were your example notebook and had the same problem.

In the meantime, I realized that I can't see any data when using  `ipyleaflet.LocalTileLayer` . `ImageOverlay` is ok though.

I tried different [things](https://github.com/jupyter-widgets/ipyleaflet/issues/427) but can't get my head around this.  Need to dig in a bit further.

If you have any clues as to why this could be, they would be much appreciated.

If I find a solution I'll share here too.

Thank you! 

Cheers
Rosa

**Comment by rosatrancoso** [comment]
Hi David

Thank you for your swift reply. Indeed it makes sense it needs a projection. 

It works now, but only with JupyerNotebook, not with JupyterLab.  It seems that, for JupyterLab, `LocalTileLayer` needs to have `path='files/{full_path_since_notebook_origin}/{z}/{x}/{y}.png'` (following [ipyleaflet issue](https://github.com/jupyter-widgets/ipyleaflet/issues/427))

I ran your [example notebooks](https://github.com/davidbrochart/ipyspin/blob/master/examples/) on Jupyter Notebook and they run just fine. I can the same docker image, so no problem.

Thank you so much!
Cheers
Rosa

**Comment by zxdawn** [comment]
@rosatrancoso I met the same issue in jupyterlab. Could you share how to set the `LocalTileLayer`?

For example, I have add the crs to data:
```
from ipyleaflet import Map, basemaps, LayersControl, WidgetControl

m = Map(center=[40, 115], zoom=3, basemap=basemaps.CartoDB.DarkMatter, interpolation='nearest')

data = data.rio.write_crs(4326)  # WGS 84
data = data.rio.write_nodata(np.nan)

data.leaflet.plot(m, colormap='vidiris')
```
