### ISSUE TITLE
No data display

### ISSUE THREAD

**Issue by SerRichard** [davidbrochart/xarray_leaflet#39]
Hi David,

 Enjoying the ease of use with this package, however I'm suffering the same issue as issue#36, so I'm sorry to repeat that I can't visualise any data on the map. I've tried all of your notebooks, and even Rosa's notebook with your issue#36 solution. I'm thinking maybe there is an issue with my environment set up, I've attached what I'm working with. Any help is appreciated, would love to get this package working!

´´´
!jupyter --version

jupyter core     : 4.7.0
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.16.1
ipykernel        : 5.3.0
jupyter client   : 6.1.7
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 4.3.3

!jupyter labextension list

Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
JupyterLab v2.1.3
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @bokeh/jupyter_bokeh v2.0.2  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        jupyter-leaflet v0.13.5  enabled  OK
        jupyter-matplotlib v0.7.2  enabled  OK
        keplergl-jupyter v0.2.2  enabled  OK
´´´

If I've missed something please let me know.

**Comment by davidbrochart** [comment]
Hi Sean,
It looks like you want to use JupyterLab? But I see it's not installed.

**Comment by SerRichard** [comment]
I was curious about this, but when I try !jupyter lab --version, I get back 2.1.3. 

Did a quick reinstall and now get back

!jupyter --version

jupyter core     : 4.7.0
jupyter-notebook : 6.2.0
qtconsole        : 5.0.2
ipython          : 7.16.1
ipykernel        : 5.3.0
jupyter client   : 6.1.7
jupyter lab      : 3.0.10
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 4.3.3

I've tried running the notebooks again and still don't manage to get any plots. Apologies for my noobidity, and thanks for your speedy reply :)

**Comment by davidbrochart** [comment]
I think you should start with a clean environment, and for that I recommend using conda. Here is the environment we have for the binder: https://github.com/davidbrochart/xarray_leaflet/tree/master/binder

**Comment by SerRichard** [comment]
Cheers David, I have used the build locally and it's working, so now I will try it in the Labs.

Thanks for the help!

**Comment by davidbrochart** [comment]
See #45
